version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/quote_editor
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=quote_editor_development
      - RAILS_ENV=development
    env_file:
      - .env
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: quote_editor_development
    ports:
      - "5432:5433"
    volumes:
      - /var/lib/postgres/data